let categories=[];let products=[];let excelInfo=[];
function euro(v){return v==null?'—':'€ '+Number(v).toFixed(2)}
function showTab(id){document.querySelectorAll('.tab').forEach(x=>x.classList.add('hidden'));document.getElementById(id).classList.remove('hidden')}
async function init(){categories=await fetch('/api/categories').then(r=>r.json());const cat=document.getElementById('cat');categories.forEach(c=>{const o=document.createElement('option');o.value=c;o.textContent=c;cat.appendChild(o)});document.getElementById('countCats').textContent=categories.length;const st=await fetch('/api/stats').then(r=>r.json());document.getElementById('countSuppliers').textContent=Object.keys(st.suppliers||{}).length;await loadProducts()}
async function loadProducts(){const q=document.getElementById('q')?.value||'';const category=document.getElementById('cat')?.value||'';products=await fetch(`/api/products?q=${encodeURIComponent(q)}&category=${encodeURIComponent(category)}`).then(r=>r.json());document.getElementById('countProducts').textContent=products.length;const box=document.getElementById('products');if(!box)return;box.innerHTML=products.map(p=>`<div class="product"><div><b>#${p.id} ${p.descrizione}</b><br><span class="badge">${p.categoria}</span> <span>${p.unita||''}</span></div><div><span class="price">${euro(p.prezzo)}</span><br><button onclick="detail(${p.id})">Dettaglio</button></div></div>`).join('')||'<p>Nessun prodotto trovato.</p>'}
async function detail(id){const d=await fetch('/api/product/'+id).then(r=>r.json()),b=d.bonaccini,matches=d.matches||{},alts=d.alternatives||[];let cards=`<div class="card"><h3>Bonaccini</h3><p>Prezzo da fatture</p><div class="price">${euro(b.prezzo)}</div><p>Ultimo: ${b.data_ultimo||'—'} · Qtà ${b.quantita||0}</p></div>`;Object.entries(matches).forEach(([s,m])=>cards+=`<div class="card"><h3>${s}</h3><p>Confronto diretto</p><div class="price ${b.prezzo!=null&&m.prezzo<b.prezzo?'ok':'bad'}">${euro(m.prezzo)}</div><p>${m.descrizione}${m.volume_cl?` · ${m.volume_cl} cl`:''}</p></div>`);const groups={};alts.forEach(a=>(groups[a.supplier]??=[]).push(a));const tables=Object.entries(groups).map(([s,arr])=>`<h3>Alternative ${s}: solo ${b.categoria}</h3><table><thead><tr><th>Prodotto</th><th>Formato</th><th>Prezzo</th></tr></thead><tbody>${arr.map(a=>`<tr><td>${a.descrizione}</td><td>${a.unita||''}</td><td>${euro(a.prezzo)}</td></tr>`).join('')}</tbody></table>`).join('');document.getElementById('detail').innerHTML=`<div class="detail"><h2>${b.descrizione}</h2><p><span class="badge">${b.categoria}</span></p><div class="grid">${cards}</div>${tables||'<p>Nessuna alternativa disponibile della stessa categoria.</p>'}</div>`;document.getElementById('detail').scrollIntoView({behavior:'smooth'})}
async function previewSupplier(){const f=document.getElementById('supplierFile').files[0];if(!f){alert('Scegli prima un file Excel');return}const fd=new FormData();fd.append('kind','listini');fd.append('file',f);const res=await fetch('/api/upload',{method:'POST',body:fd}).then(r=>r.json());if(!res.ok){document.getElementById('uploadResult').textContent=res.error||'Errore';return}excelInfo=res.sheets||[];const sheet=document.getElementById('sheetName');sheet.innerHTML=excelInfo.map(x=>`<option value="${escapeHtml(x.name)}">${escapeHtml(x.name)}</option>`).join('');sheet.onchange=fillColumns;document.getElementById('excelOptions').classList.remove('hidden');fillColumns();}
function escapeHtml(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function fillColumns(){const info=excelInfo.find(x=>x.name===document.getElementById('sheetName').value)||excelInfo[0];const sels=[document.getElementById('productCol'),document.getElementById('priceCol'),document.getElementById('volumeCol')];sels.forEach((sel,j)=>{sel.innerHTML=j===2?'<option value="">Nessuna</option>':'';(info?.headers||[]).forEach((h,i)=>{const o=document.createElement('option');o.value=i;o.textContent=`${i+1} — ${h||'(senza titolo)'}`;sel.appendChild(o)})});const h=(info?.headers||[]).map((x,i)=>`${i+1}. ${x}`).join(' | ');document.getElementById('excelPreview').textContent=`Colonne: ${h}\n\nAnteprima:\n`+(info?.preview||[]).map(r=>r.join(' | ')).join('\n');autoPick(info?.headers||[]);}
function autoPick(headers){const find=keys=>{for(let i=0;i<headers.length;i++){const h=String(headers[i]||'').toLowerCase();if(keys.some(k=>h.includes(k)))return String(i)}return ''};document.getElementById('productCol').value=find(['descrizione','prodotto','articolo','descr','voce','nome','merce']);document.getElementById('priceCol').value=find(['prezzo','price','costo','€','euro','listino']);const v=find(['volume','formato','litri','lt','cl','ml','quantita','quantità']);if(v!=='')document.getElementById('volumeCol').value=v;}
async function importSupplier(){const file=document.getElementById('supplierFile').files[0];const supplier=document.getElementById('supplierName').value.trim();if(!file||!supplier){alert('Inserisci fornitore e file');return}const fd=new FormData();fd.append('supplier',supplier);fd.append('file',file);fd.append('sheet',document.getElementById('sheetName').value);fd.append('product_col',document.getElementById('productCol').value);fd.append('price_col',document.getElementById('priceCol').value);fd.append('volume_col',document.getElementById('volumeCol').value);const res=await fetch('/api/import-supplier',{method:'POST',body:fd}).then(r=>r.json());document.getElementById('uploadResult').textContent=JSON.stringify(res,null,2);if(res.ok){alert(`Importazione completata: ${res.inserted} nuovi, ${res.updated} aggiornati.`);const st=await fetch('/api/stats').then(r=>r.json());document.getElementById('countSuppliers').textContent=Object.keys(st.suppliers||{}).length}}
init();
